name: Test infrastructure
on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  create:
    name: Create resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ./terraform/aws
      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform/aws
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform/aws

      - name: Upload Terraform state
        uses: actions/upload-artifact@v4
        with:
          name: terraform_state
          path: ./terraform/aws/terraform.tfstate

  test:
    name: Infrastructure tests
    needs: create
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300
  
  destroy:
    name: Destroy resources
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Terraform state
        uses: actions/download-artifact@v4
        with:
          name: terraform_state
          path: ./terraform/aws

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform/aws
      - name: Destroy Terraform configuration
        run: terraform destroy -auto-approve
        working-directory: ./terraform/aws