name: Test infrastructure
on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "ani-hcp"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "awi-infra-guard-workspace"
  CONFIG_DIRECTORY: "./terraform"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
    - uses: actions/checkout@v3

    - name: Upload Configuration
      uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
      id: apply-upload
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        directory: ${{ env.CONFIG_DIRECTORY }}
    - name: Create Apply Run
      uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
      id: aplly-run
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
    - name: Apply
      uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
      id: apply
      with:
        run: ${{ steps.apply-run.outputs.run_id }}
        comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"