name: Test using AWS infrastructure
on:
  workflow_dispatch:
    inputs:
      self_hosted_runner_name:
        description: 'Self-hosted runner name'
        required: true

jobs:
  test:
    name: Infrastructure tests
    runs-on: [self-hosted, "${{ github.event.inputs.self_hosted_runner_name }}"]
    steps:
      - name: Check if gRPC server is ready
        run: |
          if grpc_cli ls localhost:50052 | grep -q "infra.CloudProviderService"; then
            echo "gRPC server ready"
          fi

      - name: Check if VPC exists
        run: |
          if grpc_cli call localhost:50052 ListVPC "provider: 'aws', region: 'us-east-2'" | grep -q "vpc-025f05e7507dde253"; then
            echo "OK"
          else
            echo "FAIL"
          fi