name: Test using AWS infrastructure
on:
  workflow_dispatch:
    inputs:
      self_hosted_runner_name:
        description: 'Self-hosted runner name'
        required: true

jobs:
  test:
    name: Infrastructure tests
    runs-on: [self-hosted, "${{ github.event.inputs.self_hosted_runner_name }}"]
    steps:
      - name: Check if gRPC server is ready
        run: |
          if grpc_cli ls localhost:50052 | grep -q "infra.CloudProviderService"; then
            echo "gRPC server ready"
          fi

      - name: Run tests
        run: ./test_list_instances.sh
        working-directory: ./terraform/aws/tests